### ISSUE TITLE
Fleet Sidekick scheduling fails with "Wants" directive.

### ISSUE THREAD

**Issue by sukrit007** [coreos/fleet#1079] opened 2015-01-02 06:08 UTC
**Given**:  Main application unit file that "Wants" side kick service
```
[Unit]
Description=My Apache Frontend
After=docker.service
Requires=docker.service
Wants=apache-discovery@%i.service
[Service]
TimeoutStartSec=0
ExecStartPre=-/usr/bin/docker kill apache1
ExecStartPre=-/usr/bin/docker rm apache1
ExecStartPre=/usr/bin/docker pull coreos/apache
ExecStart=/usr/bin/docker run -rm --name apache1 -p 80:80 coreos/apache /usr/sbin/apache2ctl -D FOREGROUND
ExecStop=/usr/bin/docker stop apache1

[X-Fleet]
Conflicts=apache@*.service
```

**And**: Sidekick unit  that binds to application service.
```
[Unit]
Description=Announce Apache1
BindsTo=apache@%i.service
After=apache@%i.service

[Service]
ExecStart=/bin/sh -c "while true; do etcdctl set /services/website/apache@%i '{ \"host\": \"%H\", \"port\": 80, \"version\": \"52c7248a14\" }' --ttl 60;sleep 45;done"
ExecStop=/usr/bin/etcdctl rm /services/website/apache@%i

[X-Fleet]
MachineOf=apache@%i.service
```

**When**: I submit and start the app unit and sidekicks
```shell
fleetctl submit apache\@.service
fleetctl submit apache-discovery\@.service
fleetctl start apache@{1..1}.service
fleetctl start apache-discovery@{1..1}.service
```
 
**Then**:  My sidekick fails to start
```
fleetctl status apache-discovery@1.service 
● apache-discovery@1.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
Jan 02 05:45:37 ip-10-249-144-233.us-west-1.compute.internal systemd[1]: Cannot add dependency job for unit apache-discovery@1.service, ignoring: Unit apache-discovery@1.service failed to load: No such file or directory.
```

**Env. Info**
VERSION=549.0.0
EC2 AMI=  us-east: ami-72ddb71a
CLUSTER_SIZE = 2
INSTANCE_SIZe = m3.medium
FLEET = 0.9.0

**Notes**  
It works on COREOS 472.0 fleet 0.8.3  but stopped working after upgrade to 549.0.0 , fleet 0.9.0

**Comment by sukrit007** [comment] 2015-01-05 10:05
After adding fleetctl load prior to start,  it started working as before. : 
fleetctl load apache@{1..1}.service
fleetctl load apache-discovery@{1..1}.service
fleetctl start apache@{1..1}.service
fleetctl start apache-discovery@{1..1}.service

**Comment by brianredbeard** [comment] 2015-01-09 23:14
@sukrit007 can you also post the contents of `/etc/os-release`?

**Comment by sukrit007** [comment] 2015-01-09 23:59
/etc/os-release: 

```
NAME=CoreOS
ID=coreos
VERSION=550.0.0
VERSION_ID=550.0.0
BUILD_ID=
PRETTY_NAME="CoreOS 550.0.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

**Comment by msumme** [comment] 2015-02-05 02:22
Any updates on this?  I'm having this issue as well.
```
NAME=CoreOS
ID=coreos
VERSION=557.2.0
VERSION_ID=557.2.0
BUILD_ID=
PRETTY_NAME="CoreOS 557.2.0"
ANSI_COLOR="1;32"
HOME_URL="https://coreos.com/"
BUG_REPORT_URL="https://github.com/coreos/bugs/issues"
```

**Comment by msumme** [comment] 2015-02-05 17:15
This seems an awful lot like this: https://github.com/coreos/fleet/issues/412

Which as far as I can tell was never _actually_ resolved - just closed?

**Comment by sukrit007** [comment] 2015-02-05 17:43
While using https://coreos.com/releases/#452.0.0, I did not run into this issue. I directly upgraded to CoreOS 550.0.0.  Something tells me that one of the release between that broke it.

**Comment by msumme** [comment] 2015-02-05 18:18
I tried the "systemctl daemon-reload" solution - and it sometimes left fleet in an unstable state that could not start, stop, or destroy units.

That could also have something to do with memory limits on the machine in question.

**Comment by sukrit007** [comment] 2015-02-06 01:04
So for me daemon-reload works fine, but still it does not bring back the stopped services (even with Restart=always).  Finally I decided to wrote a hack service which runs every 2 minutes and  performs daemon reload followed by starting of stopped services  that contains @[0-9] that were loaded, but not running.   (Its hacky , but kind of works for now until this issue is addressed)

https://gist.github.com/sukrit007/574bfb21fea7bdf1711f

**Comment by bcwaldon** [comment] 2015-02-09 18:48
I believe this is a duplicate of https://github.com/coreos/fleet/issues/997

**Closed** 2015-02-09 18:48 UTC

**Comment by ryantanner** [comment] 2015-02-13 10:22
I've been seeing this behavior as well ever since fleet upgraded to 0.9.0.  For us, `sudo systemctl daemon-reload` and starting the affected unit has been working.

**Comment by hunt** [comment] 2015-02-19 22:21
Have the same problem with CoreOS stable (557.2.0) some time daemon-reload help and sometime not!
Now effected with my production cluster and still cannot find any solution
