### ISSUE TITLE
fleetctl: get statuses (and restart) of the global unit

### ISSUE THREAD

**Issue by kayrus** [coreos/fleet#1559] opened 2016-04-19 08:47 UTC
At the moment it is not possible to get status of the global unit. fleetctl returns `Unable to determine status of global unit global.service.` error message. The workaround it to use `fleetctl ssh 6abfab3268cf6bb745b0aaf5da9b0cad systemctl status global.service`, which is too tricky.

I suggest to get all machines where global unit is executed and iterate through them. This will potentially create a long running process when you have thousands of machines in the cluster, and that is why we have to implement `machineid/hostname/machineIP` filter.

This solution will allow us to restart global units as well (we will use same code as in `fleetctl/status.go`). And we can resolve #975. `fleetctl ssh <whatever> sudo systemctl restart <whatever>` looks too tricky. When you need to restart several units, you'll have to write something like:

``` sh
for u in "unit1 unit2 unit3"; do fleetctl ssh $u sudo systemctl restart $u; done
```

I don't like the solution provided in #961, because it can create several simultaneous ssh connections when you will trigger batch of units and you can not limit amount of connections. The most bug-free and simple solution is to use `status.go` code.

/cc @antrik @jonboulle @tixxdz does it sound reasonable for you?

**Comment by dongsupark** [comment] 2016-04-21 15:54
+1 for the thought that ``fleetctl restart`` would be a nice feature. There must be a better way than ``"fleetctl ssh <whatever> sudo systemctl restart"``, which is indeed tricky. Maybe after the milestone v0.13, we could work on it.

**Comment by antrik** [comment] 2016-04-21 16:47
@kayrus I still think the approach I proposed for `restart` is more appropriate. (And I'd love to implement it if I'm given permission.)

I don't have much of an opinion on using `systemctl status`... In what situations would you use it?

**Comment by antrik** [comment] 2016-04-21 16:50
Eh, the last bit was bogus. I don't know though how `fleetctl status` works right now, and what the problem is with showing the status for global units... Would have to investigate first before I can give useful answer.

**Comment by tixxdz** [comment] 2016-04-22 06:47
> @kayrus I still think the approach I proposed for restart is more appropriate. (And I'd love to implement it if I'm given permission.)

Please go ahead there are no such permissions, just code the feature if you think that your solution is the best, or show something.

**Comment by dongsupark** [comment] 2016-05-30 15:13
I just added this PR to milestone v1.0, as it has been requested since quite a long time. We need to somehow add this stuff.

**Comment by dongsupark** [comment] 2016-12-16 06:57
Closed via https://github.com/coreos/fleet/pull/1624

**Closed by dongsupark** 2016-12-16 06:57 UTC
Labels: area/usability, component/fleetctl, help wanted, kind/enhancement
