### ISSUE TITLE
improve experience working with template units

### ISSUE THREAD

**Issue by jonboulle** [coreos/fleet#969] opened 2014-10-14 17:29 UTC
It should not be possible for template units to be scheduled to a system. Right now the experience is not great; it will be scheduled, but then cause chronic issues with the agent on that machine, e.g.:
```
Oct 14 17:26:41 core-01 fleetd[557]: ERROR generator.go:51: Failed fetching current unit states: Unit name foo@.service is not valid.
Oct 14 17:26:42 core-01 fleetd[557]: ERROR generator.go:51: Failed fetching current unit states: Unit name foo@.service is not valid.
Oct 14 17:26:43 core-01 fleetd[557]: ERROR generator.go:51: Failed fetching current unit states: Unit name foo@.service is not valid.
```
(Really, _any_ unit with a bad name should never be scheduled; but fleetctl should now block all bad names except for template units).

Related: #541

**Comment by efuquen** [comment] 2015-02-05 04:15
+1 on this issue.  The above comment of running `fleetctl destroy foo@.service` to resolve this issue does **not** work.  I still get errors in the journal ever few seconds like this:

`ERROR reconcile.go:80: Unable to determine agent's current state: failed fetching unit states from UnitManager: Unit name foo@.service is not valid.`

I also tried restarted fleetd and that still didn't work.  I'm running the latest CoreOS alpha channel version, 575.0.0, which includes fleetd 0.9.0 and etcd 0.4.6.  Regardless of any fix to prevent invalid template names it shouldn't take a full system restart to resolve this.

**Comment by kayrus** [comment] 2015-02-18 12:57
Have the same issue.

```
Feb 16 14:47:31 coreos3 fleetd[20310]: ERROR reconcile.go:80: Unable to determine agent's current state: failed fetching unit states from UnitManager: Unit name servicename@.service is not valid.
```
Can not remove it. Is there a temporarily solution to remove invalid service?

**Comment by BugRoger** [comment] 2015-02-20 09:59
A workaround that I found is to just delete the broken units manually. Something like:

```
find / -name "mnt@*.mount" | xargs rm
systemctl daemon-reload
systemctl restart fleet
```

**Comment by radek-senfeld** [comment] 2015-02-20 12:16
Purging /run/fleet/units did solve the problem indeed! There are also symlinks in /run/systemd/system. Also tried to remove keys from etcd at first but it didn't help..

```
etcdctl ls _coreos.com/fleet/unit
```

**Comment by chrisfarms** [comment] 2015-03-10 21:00
I am *not* doing `fleetctl start template@.service`.

I am doing `fleetctl submit template@.service`, followed later by multiple `fleetctl start template@N.service` where N is a number 0 - 5.

This works fine 95% of the time, but every now and then one of my nodes will get stuck in the `Failed fetching current unit states` referencing the `template@.service` unit.

The only thing I can think of is some kind of race condition between the `submit` and the `start` calls, but I cannot reliably recreate it at present.

(fleet 0.9.0 / coreos 557.2.0)

**Comment by HarryR** [comment] 2015-03-21 16:20
I ran into this problem today with CoreOS 612.1.0 and fleet 0.9.1 in a similar situation.

I submitted template@.service then started an instance of template@1.service, after starting another service the `fleetctl` command was hanging whenever I tried to do anything, on one machine it was repeating `Failed fetching current unit states` in `journalctl.

**Comment by hauptmedia** [comment] 2015-03-31 14:42
The problem still exists in CoreOS 633.1.0 & fleet 0.9.1. I submitted a template@.service file via fleetctl and started an instance of template@1.service. After that fleetctl hangs when it tries to schedule work on a specific machine. 

In the journal of this machine you can read:

coreos-1 core # journalctl -u fleet -f

(...) fleetd[10224]: ERROR reconcile.go:81: Unable to determine agent's current state: failed fetching unit states from UnitManager: Unit name template@.service is not valid.

**Comment by maccman** [comment] 2015-04-06 02:22
We're having exactly the same problem with the same error msg.

**Comment by geniousphp** [comment] 2015-04-19 12:48
I still get the same message error like you guys, I'm running coreos 647.0.0. Is there any clean solution ?

**Comment by duffqiu** [comment] 2015-04-23 03:11
follow @BugRoger 's suggestion, but need to change the command to your fleet unit name.

the correct path in coreos is:

/run/fleet/units/<your unit file>
/run/systemd/<your unit file>
/run/systemd/system/<your unit file>

and then reboot all your feet server in the cluster

Maybe I found the root cause it I run the fleetctl with root user.

**Comment by duffqiu** [comment] 2015-04-23 03:17
we need to run the fleetctl command with core user name.
and if you run it with root user, you need to clean the unit files manually before switch wot core user. because the core user can't delete the unit files in the system.

**Comment by rosskukulinski** [comment] 2015-04-23 22:13
FWIW, ran into this issue today  -- accidentally started service@.service.  Subtly caused problems that took a while to find the root cause of.  HUGE nightmare.

**Comment by Vish0007** [comment] 2015-06-23 10:21
@duffqiu,  do we need to restart fleet on entire cluster or just on the nodes where the 'template' units are started by fleet?
Is there a way i can reload the fleet daemon without restarting (like system daemon-reload)?

**Comment by duffqiu** [comment] 2015-06-23 10:26
@Vish0007  just need to clean the template unit(s) in the specific node and restart the fleet

I don't find the way to reload teh daemon without restart, you can find it, please tell me.

**Comment by Vish0007** [comment] 2015-06-23 10:45
would this only reload the fleet.conf?
systemctl kill -s SIGHUP fleet

**Comment by duffqiu** [comment] 2015-06-24 05:42
I am not sure if `systemctl kill -s SIGHUP fleet` or not. Anyone can help?

**Comment by beginrescueend** [comment] 2015-06-24 19:23
This still exists in 681.2.0.

**Comment by arthur-c** [comment] 2015-06-26 14:07
I accidently ran a template, @beginrescueend trick solved the problem.

**Comment by spiddy** [comment] 2015-07-16 08:46
I just hit with the same issue. Because the solution is a combination of all the above, I put it here for the next victims:

* First you need to remove the misconfigured template from fleet (otherwise it will bite you again)

```
fleetctl destroy templatename@.service
```

* Then clean the local service file and restart fleet:

```
sudo rm /run/fleet/units/templatename\@.service
sudo systemctl daemon-reload
sudo systemctl restart fleet
```

Is there a roadmap on how to fix this permanently?

**Comment by sukrit007** [comment] 2015-07-18 23:57
Just ran into this issue in latest stable version of CoreOS : 
```
DISTRIB_ID=CoreOS
DISTRIB_RELEASE=717.3.0
DISTRIB_CODENAME="Red Dog"
DISTRIB_DESCRIPTION="CoreOS 717.3.0"
```

Though cleaning the unit, daemon-reload and followed by restart fleet fixes this issue , but  running into this a lot more frequently with 717.3.0 update.

**Comment by knguyen142** [comment] 2015-07-29 02:15
I'm running into this issue too, at `717.3.0`. Restarting fleet seems to reshuffle the containers on the machine, so I don't think that's a viable solution for us. Any other ideas on how to fix?

**Comment by yhzhao** [comment] 2015-09-27 02:37
Running into the same nightmare just now. Any plan this bug get fixed?

**Comment by lfittl** [comment] 2015-09-27 23:14
@yhzhao I think this was fixed in https://github.com/coreos/fleet/pull/1273 / [release 0.11.0](https://github.com/coreos/fleet/releases/tag/v0.11.0)

CoreOS beta+stable images are still on fleet 0.10, but I assume they will move to 0.11 soon-ish.

**Comment by polvi** [comment] 2015-09-30 15:04
yes, alpha is shipping 0.11.5 and will be promoted to beta soon.

**Comment by sukrit007** [comment] 2016-02-23 04:57
So far I have not seeing this issue with 0.11.5 .  Any reason it is still open ?  Is there any other scenario (0.11.5 release) in which this can still occur ?

**Comment by jonboulle** [comment] 2016-02-23 11:38
thanks for the ping, closing

**Closed** 2016-02-23 11:38 UTC
Labels: kind/bug, priority/P1
