### ISSUE TITLE
Feature Request: fleetctl error if service doesn't exist

### ISSUE THREAD

**Issue by rosskukulinski** [coreos/fleet#1112] opened 2015-01-29 00:13 UTC
fleetctl version 0.9.0

When starting a service, fleetctl will happily tell you that the service doesn't exist:

```
$ fleetctl start myunknownsevice
Error creating units: unable to find Unit(myunknownsevice.service) in Registry or on filesystem
```

However, if you try to stop, destroy or unload a service that doesn't exist, fleetctl simply exits with an exit_code of 0.

I think that stop, unload, and destroy should print an error and return non-zero exit code.

**Comment by bcwaldon** [comment] 2015-02-09 18:51
Duplicate of https://github.com/coreos/fleet/issues/745

**Closed by bcwaldon** 2015-02-09 18:51 UTC
