### ISSUE TITLE
etcd timeout in logs trying to reach etcd dedicated cluster

### ISSUE THREAD

**Issue by danielschonfeld** [coreos/fleet#1231] opened 2015-05-18 17:50 UTC
Hello,

We've been plagued by this problem pretty much forever.  It seems that at times, fleet on a random node would be unable to reach our dedicated etcd cluster.  That cluster runs on 3 computers, n1-standard-1 (GCE) and currently uses etcd 2.  We've raised the `etcd_request_timeout` to `3`.  It seems that etcd is intact available and to make things worse - it seems like when fleet does get into this problem, it consistently tries the same etcd server (or so the logs show) and doesn't even attempt to reach any other of the two servers.

Here's a sample of the logs, and the problem this causes is evident at the end where fleet shuts itself down and restarts and therefore causes all units to be unscheduled and reloaded.

Fleet ver used is both `0.9.1` and `0.10.1`.  This problem did occur when the cluster was composed entirely of version `0.9.1` and a bunch of fleet versions prior to that.

```
May 15 16:27:07 gambit.c.my-project.internal fleetd[628]: ERROR server.go:185: Server monitor triggered: Monitor timed out before successful heartbeat
May 15 16:27:07 gambit.c.my-project.internal fleetd[628]: INFO server.go:153: Establishing etcd connectivity
May 15 16:27:07 gambit.c.my-project.internal fleetd[628]: INFO server.go:164: Starting server components
May 15 16:27:07 gambit.c.my-project.internal fleetd[628]: INFO engine.go:82: Engine leadership changed from 223fb322c5f1b7c8bae722df3af878b4 to 89c4c409a46f0330f0f7df179e076ab0
May 16 03:55:04 gambit.c.my-project.internal fleetd[628]: ERROR engine.go:150: Unable to determine cluster engine version
May 16 03:55:04 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:00:26 gambit.c.my-project.internal fleetd[628]: ERROR engine.go:150: Unable to determine cluster engine version
May 17 17:00:31 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:00:56 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:01:08 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:01:23 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:01:46 gambit.c.my-project.internal fleetd[628]: ERROR engine.go:150: Unable to determine cluster engine version
May 17 17:02:07 gambit.c.my-project.internal fleetd[628]: ERROR reconcile.go:122: Failed fetching Units from Registry: timeout reached
May 17 17:04:09 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:04:27 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:04:32 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:04:37 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:05:48 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:06:02 gambit.c.my-project.internal fleetd[628]: ERROR reconcile.go:75: Unable to determine agent's desired state: timeout reached
May 17 17:06:10 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:06:13 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:06:26 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:06:28 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:06:29 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:06:31 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:06:32 gambit.c.my-project.internal fleetd[628]: WARN reconcile.go:61:
May 17 17:06:34 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:06:36 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:06:38 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:06:39 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:06:41 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:06:44 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:06:45 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:06:47 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:06:50 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:06:51 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:06:53 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:06:54 gambit.c.my-project.internal fleetd[628]: ERROR server.go:185: Server monitor triggered: Monitor timed out before successful heartbeat
May 17 17:06:56 gambit.c.my-project.internal fleetd[628]: INFO server.go:153: Establishing etcd connectivity
May 17 17:06:58 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:07:00 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:07:04 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:07:06 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:07:10 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:07:13 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:07:16 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:07:19 gambit.c.my-project.internal fleetd[628]: INFO client.go:291: Failed getting response from http://etcd1:4001/: cancelled
May 17 17:08:35 gambit.c.my-project.internal systemd[1]: fleet.service holdoff time over, scheduling restart.
May 17 17:08:35 gambit.c.my-project.internal systemd[1]: Stopping fleet daemon...
May 17 17:08:35 gambit.c.my-project.internal systemd[1]: Starting fleet daemon...
May 17 17:08:35 gambit.c.my-project.internal systemd[1]: Started fleet daemon.
May 17 17:08:35 gambit.c.my-project.internal fleetd[15346]: INFO fleet.go:58: Starting fleetd version 0.9.1
May 17 17:08:35 gambit.c.my-project.internal fleetd[15346]: INFO fleet.go:159: Using default config file /etc/fleet/fleet.conf
```

**Comment by Telvary** [comment] 2015-06-08 15:43
I'm facing the same issue. I also tried to use a local etcd proxy but I end with the same issue (etcd proxy gets a lot of "zero endpoints currently available". 
Cluster looks healthy, tried with etcd master and fleet 0.10.1.

**Comment by bcwaldon** [comment] 2015-07-09 22:12
1. The behavior of fleet is working as intended. When fleet cannot communicate with etcd, it cannot safely proceed with the work it is currently running (#1289)
2. The issue with not attempting all etcd endpoints should have been addressed by switching to the official client (github.com/coreos/etcd/client) in #1212

**Closed** 2015-07-09 22:12 UTC
Labels: support-request

**Comment by joshk0** [comment] 2015-10-20 21:56
Can #1212 be backported to CoreOS stable?

We just got hit by this: The first server in the etcd_servers parameter went down (was taken down explicitly by us for a long maintenance window), and all fleet communication failed, without any contact to the remaining 2 servers in the cluster.

The fact that a stable version of fleet cannot benefit from etcd redundancy really blows me away. I understand that the new etcd client caused a lot of line churn. But I've been in this position with bugs of similar severity in enterprise software, and the charter there is clear:

Reduce the risk by backporting the fix or even creating an alternate, less dangerous fix for the stable channel.

**Comment by mischief** [comment] 2015-10-22 21:15
@joshk0 if you wished to use a newer fleet, you could download or build binaries and place them on your CoreOS stable machines. alternatively, you could mix some beta/alpha machines into your cluster.

**Comment by joshk0** [comment] 2015-11-06 16:46
> The issue with not attempting all etcd endpoints should have been addressed by switching to the official client (github.com/coreos/etcd/client) in #1212

@bcwaldon, we are doing risk assessment for upgrading our etcd client library. I recognize the old one is no longer maintained but we have a lot of service discovery tooling on it. Can you point to an issue or a pull request that demonstrates the bug you are talking about in this point so we can understand what we're missing out on with the old library?

Thank you very much.

**Comment by joshk0** [comment] 2015-11-06 16:48
BTW, my suspicion is that the old library works just fine as long in this regard as long as you remember to call `client.SyncCluster()`. Maybe that's implicit in the new one.
