### ISSUE TITLE
fleetctl(v0.10.1) status unit command cannot find the unit files

### ISSUE THREAD

**Issue by wuqixuan** [coreos/fleet#1224] opened 2015-05-13 15:06 UTC
I run fleetctl status, but it cannot find the unit name. Actually, the unit is there, and can find it using "fleetctl list-units" and "systemctl status unit"

<b>First it fails when using fleet status hello.service: </b>
<code>
[root@localhost fleet-0.10.1]# ../fleet-v0.10.1-linux-amd64/fleetctl --endpoint="http://127.0.0.1:4001" status hello.service
</code>
<code>
\x22hello.service\x22.service
</code>
<code>
   Loaded: not-found (Reason: No such file or directory)
</code>
<code>
   Active: inactive (dead)
</code>
<code>
[root@localhost fleet-0.10.1]#
</code>

<b>But we can find it using "fleetctl list-units". </b>

<code>
[root@localhost fleet-0.10.1]# ../fleet-v0.10.1-linux-amd64/fleetctl --endpoint="http://127.0.0.1:4001" list-units
</code>
<code>
UNIT            MACHINE                         ACTIVE  SUB
</code>
<code>
hello.service   d8e08450.../192.168.1.105       active  running
</code>

<b>Also we can find it using "systemctl status unit". </b>
<code>
[root@localhost fleet-0.10.1]# systemctl status -l hello.service
</code>
<code>
hello.service - Hello World
</code>
<code>
   Loaded: loaded (/run/fleet/units/hello.service; linked-runtime)
</code>
<code>
   Active: active (running) since Wed 2015-03-04 18:13:29 EST; 1h 21min ago
</code>
<code>
 Main PID: 28394 (bash)
</code>
<code>
   CGroup: /system.slice/hello.service
</code>
<code>
           ├─15449 sleep 1
</code>
<code>
           └─28394 /bin/bash -c while true; do echo "Hello, world"; sleep 1; done
</code>

**Comment by spesnova** [comment] 2015-06-01 06:23
I got same error:

```
core@core-01 ~ $ fleetctl -version
fleetctl version 0.10.1
```

```
core@core-01 ~ $ fleetctl list-unit-files
UNIT		HASH	DSTATE		STATE		TARGET
hello@1.service	4b9f0a0	launched	launched	710c9194.../172.17.8.101
```

```
core@core-01 ~ $ fleetctl list-units
UNIT		MACHINE				ACTIVE	SUB
hello@1.service	710c9194.../172.17.8.101	active	running
```

```
core@core-01 ~ $ systemctl status hello@1.service
● hello@1.service - Useless infinite loop
   Loaded: loaded (/run/fleet/units/hello@1.service; linked-runtime; vendor preset: disabled)
   Active: active (running) since Mon 2015-06-01 13:55:48 JST; 24s ago
 Main PID: 11693 (bash)
   CGroup: /system.slice/system-hello.slice/hello@1.service
           ├─11693 /bin/bash -c while true; do sleep 1; done
           └─11740 sleep 1

Jun 01 13:55:48 core-01 systemd[1]: Started Useless infinite loop.
Jun 01 13:55:48 core-01 systemd[1]: Starting Useless infinite loop...
```

```
core@core-01 ~ $ fleetctl status hello@1.service
● \x22hello@1.service\x22.service
   Loaded: not-found (Reason: No such file or directory)
   Active: inactive (dead)
```

and +1 for the pull request

**Comment by EtienneBruines** [comment] 2015-06-18 19:13
Your fix was merged, so I think we can close this one?

**Comment by crawford** [comment] 2015-06-18 22:09
Duplicate of https://github.com/coreos/fleet/issues/1208.

**Closed by crawford** 2015-06-18 22:09 UTC
