### ISSUE TITLE
Fleet units failing unexpectedly - CoreOS 557.2.0

### ISSUE THREAD

**Issue by imjacobclark** [coreos/fleet#1144] opened 2015-03-08 16:15 UTC
I am running Fleet on Digital Ocean, every so often I see units failing and my services going down unexpectedly, today I reviewed the logs and there seems to be no indication of what is going wrong.

The units fail to come back up unless I `systemctl restart fleet`, I have `Restart=always` within each unit file.

journal logs since failure:
```
Mar 08 16:07:14 do-coreos01-master fleetd[608]: INFO manager.go:145: Triggered systemd unit blog-jacob-uk-com-discovery@90.service stop: job=44337
Mar 08 16:07:14 do-coreos01-master fleetd[608]: INFO manager.go:275: Removing systemd unit blog-jacob-uk-com-discovery@90.service
Mar 08 16:07:14 do-coreos01-master systemd[1]: Stopping Nginx Instance for CoreOS platform...
Mar 08 16:07:14 do-coreos01-master systemd[1]: Stopping Developer News API...
Mar 08 16:07:14 do-coreos01-master systemd[1]: Stopping Announce devnews-core@82 service...
Mar 08 16:07:14 do-coreos01-master systemd[1]: Stopping Ghost instance for jacob.uk.com...
Mar 08 16:07:14 do-coreos01-master systemd[1]: Stopping Announce blog-jacob-uk-com@90 service...
Mar 08 16:07:14 do-coreos01-master systemd[1]: Stopped Announce blog-jacob-uk-com@90 service.
Mar 08 16:07:14 do-coreos01-master systemd[1]: devnews-core-discovery@82.service: control process exited, code=exited status=4
Mar 08 16:07:14 do-coreos01-master systemd[1]: Stopped Announce devnews-core@82 service.
Mar 08 16:07:14 do-coreos01-master systemd[1]: Unit devnews-core-discovery@82.service entered failed state.
Mar 08 16:07:14 do-coreos01-master systemd[1]: devnews-core-discovery@82.service failed.
Mar 08 16:07:14 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:14Z" level="info" msg="POST /v1.16/containers/blog-jacob-uk-com90/stop?t=10"
Mar 08 16:07:14 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:14Z" level="info" msg="+job stop(blog-jacob-uk-com90)"
Mar 08 16:07:14 do-coreos01-master fleetd[608]: INFO manager.go:145: Triggered systemd unit blog-jacob-uk-com@90.service stop: job=44338
Mar 08 16:07:14 do-coreos01-master fleetd[608]: INFO manager.go:145: Triggered systemd unit devnews-core@82.service stop: job=44341
Mar 08 16:07:14 do-coreos01-master fleetd[608]: INFO manager.go:145: Triggered systemd unit devnews-core-discovery@82.service stop: job=44342
Mar 08 16:07:14 do-coreos01-master fleetd[608]: INFO manager.go:145: Triggered systemd unit nginx.service stop: job=44345
Mar 08 16:07:14 do-coreos01-master fleetd[608]: INFO manager.go:275: Removing systemd unit blog-jacob-uk-com@90.service
Mar 08 16:07:14 do-coreos01-master fleetd[608]: INFO reconcile.go:321: AgentReconciler completed task: type=UnloadUnit job=blog-jacob-uk-com-discovery@90.service reason="unit loa
Mar 08 16:07:14 do-coreos01-master fleetd[608]: INFO manager.go:275: Removing systemd unit devnews-core@82.service
Mar 08 16:07:14 do-coreos01-master fleetd[608]: INFO reconcile.go:321: AgentReconciler completed task: type=UnloadUnit job=blog-jacob-uk-com@90.service reason="unit loaded but noMar 08 16:07:14 do-coreos01-master fleetd[608]: INFO manager.go:275: Removing systemd unit devnews-core-discovery@82.service
Mar 08 16:07:14 do-coreos01-master fleetd[608]: INFO reconcile.go:321: AgentReconciler completed task: type=UnloadUnit job=devnews-core@82.service reason="unit loaded but not schMar 08 16:07:14 do-coreos01-master fleetd[608]: INFO manager.go:275: Removing systemd unit nginx.service
Mar 08 16:07:14 do-coreos01-master fleetd[608]: INFO reconcile.go:321: AgentReconciler completed task: type=UnloadUnit job=devnews-core-discovery@82.service reason="unit loaded bMar 08 16:07:14 do-coreos01-master fleetd[608]: INFO reconcile.go:321: AgentReconciler completed task: type=UnloadUnit job=nginx.service reason="unit loaded but not scheduled herMar 08 16:07:14 do-coreos01-master etcdctl[26491]: Error:  100: Key not found (/announce) [545075]
Mar 08 16:07:14 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:14Z" level="info" msg="POST /v1.16/containers/devnews-core82/stop?t=10"
Mar 08 16:07:14 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:14Z" level="info" msg="+job stop(devnews-core82)"
Mar 08 16:07:15 do-coreos01-master kernel: docker0: port 4(vetha3d2c85) entered disabled state
Mar 08 16:07:15 do-coreos01-master kernel: device vetha3d2c85 left promiscuous mode
Mar 08 16:07:15 do-coreos01-master kernel: docker0: port 4(vetha3d2c85) entered disabled state
Mar 08 16:07:15 do-coreos01-master systemd-networkd[603]: vetha3d2c85     : lost carrier
Mar 08 16:07:15 do-coreos01-master systemd-networkd[603]: vetha3d2c85     : could not find udev device: No such device
Mar 08 16:07:15 do-coreos01-master systemd[1]: Stopped Developer News API.
Mar 08 16:07:15 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:15Z" level="info" msg="+job log(die, fd3626dfdf452df41eb811ff5eaadc0026e4a16b27e32e24661834e9fa060ed2, imjMar 08 16:07:15 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:15Z" level="info" msg="-job log(die, fd3626dfdf452df41eb811ff5eaadc0026e4a16b27e32e24661834e9fa060ed2, imjMar 08 16:07:15 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:15Z" level="info" msg="+job release_interface(fd3626dfdf452df41eb811ff5eaadc0026e4a16b27e32e24661834e9fa06Mar 08 16:07:15 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:15Z" level="info" msg="-job attach(fd3626dfdf452df41eb811ff5eaadc0026e4a16b27e32e24661834e9fa060ed2) = OK Mar 08 16:07:15 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:15Z" level="info" msg="POST /v1.16/containers/fd3626dfdf452df41eb811ff5eaadc0026e4a16b27e32e24661834e9fa06Mar 08 16:07:15 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:15Z" level="info" msg="+job wait(fd3626dfdf452df41eb811ff5eaadc0026e4a16b27e32e24661834e9fa060ed2)"
Mar 08 16:07:15 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:15Z" level="info" msg="-job release_interface(fd3626dfdf452df41eb811ff5eaadc0026e4a16b27e32e24661834e9fa06Mar 08 16:07:15 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:15Z" level="info" msg="+job log(stop, fd3626dfdf452df41eb811ff5eaadc0026e4a16b27e32e24661834e9fa060ed2, imMar 08 16:07:15 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:15Z" level="info" msg="-job log(stop, fd3626dfdf452df41eb811ff5eaadc0026e4a16b27e32e24661834e9fa060ed2, imMar 08 16:07:15 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:15Z" level="info" msg="-job stop(devnews-core82) = OK (0)"
Mar 08 16:07:15 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:15Z" level="info" msg="-job wait(fd3626dfdf452df41eb811ff5eaadc0026e4a16b27e32e24661834e9fa060ed2) = OK (0Mar 08 16:07:15 do-coreos01-master docker[26490]: devnews-core82
Mar 08 16:07:15 do-coreos01-master docker[3073]: 2015-03-08T16:07:15Z 9eade23528a8 confd[44]: INFO Target config /etc/nginx/sites-enabled/devnews-core.conf has been updated
Mar 08 16:07:15 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:15Z" level="info" msg="POST /v1.16/containers/nginx/stop?t=10"
Mar 08 16:07:15 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:15Z" level="info" msg="+job stop(nginx)"
Mar 08 16:07:16 do-coreos01-master ntpd[472]: Deleting interface #15 vetha3d2c85, fe80::88e9:9aff:feab:234%12#123, interface stats: received=0, sent=0, dropped=0, active_time=225Mar 08 16:07:16 do-coreos01-master ntpd[472]: 8 Mar 16:07:16 ntpd[472]: Deleting interface #15 vetha3d2c85, fe80::88e9:9aff:feab:234%12#123, interface stats: received=0, sent=0, Mar 08 16:07:18 do-coreos01-master fleetd[608]: INFO manager.go:262: Writing systemd unit devnews-core@82.service (594b)
Mar 08 16:07:18 do-coreos01-master fleetd[608]: INFO manager.go:198: Instructing systemd to reload units
Mar 08 16:07:18 do-coreos01-master systemd[1]: Reloading.
Mar 08 16:07:19 do-coreos01-master fleetd[608]: INFO manager.go:262: Writing systemd unit nginx.service (497b)
Mar 08 16:07:19 do-coreos01-master fleetd[608]: INFO reconcile.go:321: AgentReconciler completed task: type=LoadUnit job=devnews-core@82.service reason="unit scheduled here but nMar 08 16:07:19 do-coreos01-master fleetd[608]: INFO manager.go:262: Writing systemd unit blog-jacob-uk-com-discovery@90.service (722b)
Mar 08 16:07:19 do-coreos01-master fleetd[608]: INFO reconcile.go:321: AgentReconciler completed task: type=LoadUnit job=nginx.service reason="unit scheduled here but not loaded"Mar 08 16:07:19 do-coreos01-master fleetd[608]: INFO manager.go:262: Writing systemd unit blog-jacob-uk-com@90.service (666b)
Mar 08 16:07:19 do-coreos01-master fleetd[608]: INFO reconcile.go:321: AgentReconciler completed task: type=LoadUnit job=blog-jacob-uk-com-discovery@90.service reason="unit schedMar 08 16:07:19 do-coreos01-master fleetd[608]: INFO manager.go:262: Writing systemd unit devnews-core-discovery@82.service (582b)
Mar 08 16:07:19 do-coreos01-master fleetd[608]: INFO reconcile.go:321: AgentReconciler completed task: type=LoadUnit job=blog-jacob-uk-com@90.service reason="unit scheduled here Mar 08 16:07:19 do-coreos01-master fleetd[608]: INFO reconcile.go:321: AgentReconciler completed task: type=LoadUnit job=devnews-core-discovery@82.service reason="unit scheduled Mar 08 16:07:19 do-coreos01-master fleetd[608]: ERROR manager.go:136: Failed to trigger systemd unit devnews-core@82.service start: Unit devnews-core-discovery@82.service failed Mar 08 16:07:19 do-coreos01-master fleetd[608]: INFO reconcile.go:321: AgentReconciler completed task: type=StartUnit job=devnews-core@82.service reason="unit currently loaded buMar 08 16:07:19 do-coreos01-master fleetd[608]: ERROR manager.go:136: Failed to trigger systemd unit nginx.service start: Unit nginx.service failed to load: No such file or direc...skipping...
Mar 08 16:07:15 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:15Z" level="info" msg="+job stop(nginx)"
Mar 08 16:07:16 do-coreos01-master ntpd[472]: Deleting interface #15 vetha3d2c85, fe80::88e9:9aff:feab:234%12#123, interface stats: received=0, sent=0, dropped=0, active_time=225
Mar 08 16:07:16 do-coreos01-master ntpd[472]: 8 Mar 16:07:16 ntpd[472]: Deleting interface #15 vetha3d2c85, fe80::88e9:9aff:feab:234%12#123, interface stats: received=0, sent=0, 
Mar 08 16:07:18 do-coreos01-master fleetd[608]: INFO manager.go:262: Writing systemd unit devnews-core@82.service (594b)
Mar 08 16:07:18 do-coreos01-master fleetd[608]: INFO manager.go:198: Instructing systemd to reload units
Mar 08 16:07:18 do-coreos01-master systemd[1]: Reloading.
Mar 08 16:07:19 do-coreos01-master fleetd[608]: INFO manager.go:262: Writing systemd unit nginx.service (497b)
Mar 08 16:07:19 do-coreos01-master fleetd[608]: INFO reconcile.go:321: AgentReconciler completed task: type=LoadUnit job=devnews-core@82.service reason="unit scheduled here but n
Mar 08 16:07:19 do-coreos01-master fleetd[608]: INFO manager.go:262: Writing systemd unit blog-jacob-uk-com-discovery@90.service (722b)
Mar 08 16:07:19 do-coreos01-master fleetd[608]: INFO reconcile.go:321: AgentReconciler completed task: type=LoadUnit job=nginx.service reason="unit scheduled here but not loaded"
Mar 08 16:07:19 do-coreos01-master fleetd[608]: INFO manager.go:262: Writing systemd unit blog-jacob-uk-com@90.service (666b)
Mar 08 16:07:19 do-coreos01-master fleetd[608]: INFO reconcile.go:321: AgentReconciler completed task: type=LoadUnit job=blog-jacob-uk-com-discovery@90.service reason="unit sched
Mar 08 16:07:19 do-coreos01-master fleetd[608]: INFO manager.go:262: Writing systemd unit devnews-core-discovery@82.service (582b)
Mar 08 16:07:19 do-coreos01-master fleetd[608]: INFO reconcile.go:321: AgentReconciler completed task: type=LoadUnit job=blog-jacob-uk-com@90.service reason="unit scheduled here 
Mar 08 16:07:19 do-coreos01-master fleetd[608]: INFO reconcile.go:321: AgentReconciler completed task: type=LoadUnit job=devnews-core-discovery@82.service reason="unit scheduled 
Mar 08 16:07:19 do-coreos01-master fleetd[608]: ERROR manager.go:136: Failed to trigger systemd unit devnews-core@82.service start: Unit devnews-core-discovery@82.service failed 
Mar 08 16:07:19 do-coreos01-master fleetd[608]: INFO reconcile.go:321: AgentReconciler completed task: type=StartUnit job=devnews-core@82.service reason="unit currently loaded bu
Mar 08 16:07:19 do-coreos01-master fleetd[608]: ERROR manager.go:136: Failed to trigger systemd unit nginx.service start: Unit nginx.service failed to load: No such file or direc
Mar 08 16:07:19 do-coreos01-master fleetd[608]: INFO reconcile.go:321: AgentReconciler completed task: type=StartUnit job=nginx.service reason="unit currently loaded but desired 
Mar 08 16:07:19 do-coreos01-master fleetd[608]: ERROR manager.go:136: Failed to trigger systemd unit blog-jacob-uk-com-discovery@90.service start: Unit blog-jacob-uk-com@90.servi
Mar 08 16:07:19 do-coreos01-master fleetd[608]: INFO reconcile.go:321: AgentReconciler completed task: type=StartUnit job=blog-jacob-uk-com-discovery@90.service reason="unit curr
Mar 08 16:07:19 do-coreos01-master fleetd[608]: ERROR manager.go:136: Failed to trigger systemd unit blog-jacob-uk-com@90.service start: Unit blog-jacob-uk-com@90.service failed 
Mar 08 16:07:19 do-coreos01-master fleetd[608]: INFO reconcile.go:321: AgentReconciler completed task: type=StartUnit job=blog-jacob-uk-com@90.service reason="unit currently load
Mar 08 16:07:19 do-coreos01-master fleetd[608]: ERROR manager.go:136: Failed to trigger systemd unit devnews-core-discovery@82.service start: Unit devnews-core-discovery@82.servi
Mar 08 16:07:19 do-coreos01-master fleetd[608]: INFO reconcile.go:321: AgentReconciler completed task: type=StartUnit job=devnews-core-discovery@82.service reason="unit currently
Mar 08 16:07:23 do-coreos01-master docker[3073]: 2015-03-08T16:07:23Z 9eade23528a8 confd[45]: ERROR template: blog-jacob-uk-com.tmpl:2:9: executing "blog-jacob-uk-com.tmpl" at <g
Mar 08 16:07:23 do-coreos01-master docker[3073]: 2015-03-08T16:07:23Z 9eade23528a8 confd[45]: INFO /etc/nginx/sites-enabled/devnews-core.conf has md5sum b7bc9c628e978cda7b50ade58
Mar 08 16:07:23 do-coreos01-master docker[3073]: 2015-03-08T16:07:23Z 9eade23528a8 confd[45]: INFO Target config /etc/nginx/sites-enabled/devnews-core.conf out of sync
Mar 08 16:07:23 do-coreos01-master docker[3073]: 2015-03-08T16:07:23Z 9eade23528a8 confd[45]: INFO Target config /etc/nginx/sites-enabled/devnews-core.conf has been updated
Mar 08 16:07:24 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:24Z" level="info" msg="Container f222685ed689a494f68c13e6d637343c6701b06a6bf0a479aa28489588ddd455 failed t
Mar 08 16:07:24 do-coreos01-master kernel: docker0: port 3(veth7c483f1) entered disabled state
Mar 08 16:07:24 do-coreos01-master systemd-networkd[603]: veth7c483f1     : lost carrier
Mar 08 16:07:24 do-coreos01-master kernel: device veth7c483f1 left promiscuous mode
Mar 08 16:07:24 do-coreos01-master kernel: docker0: port 3(veth7c483f1) entered disabled state
Mar 08 16:07:24 do-coreos01-master systemd-networkd[603]: veth7c483f1     : could not find udev device: No such device
Mar 08 16:07:24 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:24Z" level="info" msg="+job log(die, f222685ed689a494f68c13e6d637343c6701b06a6bf0a479aa28489588ddd455, doc
Mar 08 16:07:24 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:24Z" level="info" msg="-job log(die, f222685ed689a494f68c13e6d637343c6701b06a6bf0a479aa28489588ddd455, doc
Mar 08 16:07:24 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:24Z" level="info" msg="+job release_interface(f222685ed689a494f68c13e6d637343c6701b06a6bf0a479aa28489588dd
Mar 08 16:07:24 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:24Z" level="info" msg="-job attach(f222685ed689a494f68c13e6d637343c6701b06a6bf0a479aa28489588ddd455) = OK 
Mar 08 16:07:24 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:24Z" level="info" msg="POST /v1.16/containers/f222685ed689a494f68c13e6d637343c6701b06a6bf0a479aa28489588dd
Mar 08 16:07:25 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:24Z" level="info" msg="+job wait(f222685ed689a494f68c13e6d637343c6701b06a6bf0a479aa28489588ddd455)"
Mar 08 16:07:25 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:25Z" level="info" msg="-job release_interface(f222685ed689a494f68c13e6d637343c6701b06a6bf0a479aa28489588dd
Mar 08 16:07:25 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:25Z" level="info" msg="+job log(stop, f222685ed689a494f68c13e6d637343c6701b06a6bf0a479aa28489588ddd455, do
Mar 08 16:07:25 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:25Z" level="info" msg="-job log(stop, f222685ed689a494f68c13e6d637343c6701b06a6bf0a479aa28489588ddd455, do
Mar 08 16:07:25 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:25Z" level="info" msg="-job stop(blog-jacob-uk-com90) = OK (0)"
Mar 08 16:07:25 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:25Z" level="info" msg="-job wait(f222685ed689a494f68c13e6d637343c6701b06a6bf0a479aa28489588ddd455) = OK (0
Mar 08 16:07:25 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:25Z" level="info" msg="-job stop(blog-jacob-uk-com90) = OK (0)"
Mar 08 16:07:25 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:25Z" level="info" msg="-job wait(f222685ed689a494f68c13e6d637343c6701b06a6bf0a479aa28489588ddd455) = OK (0Mar 08 16:07:25 do-coreos01-master systemd[1]: blog-jacob-uk-com@90.service: main process exited, code=exited, status=255/n/a
Mar 08 16:07:25 do-coreos01-master docker[26492]: blog-jacob-uk-com90
Mar 08 16:07:25 do-coreos01-master systemd[1]: Stopped blog-jacob-uk-com@90.service.
Mar 08 16:07:25 do-coreos01-master systemd[1]: Unit blog-jacob-uk-com@90.service entered failed state.
Mar 08 16:07:25 do-coreos01-master systemd[1]: blog-jacob-uk-com@90.service failed.
Mar 08 16:07:25 do-coreos01-master docker[3073]: 2015-03-08T16:07:25Z 9eade23528a8 confd[44]: ERROR template: blog-jacob-uk-com.tmpl:2:9: executing "blog-jacob-uk-com.tmpl" at <gMar 08 16:07:25 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:25Z" level="info" msg="Container 9eade23528a8b23a10a3154e538ba49aa7db25d73b8cdd2127de7d0e328e2978 failed tMar 08 16:07:25 do-coreos01-master kernel: docker0: port 1(veth0eb461d) entered disabled state
Mar 08 16:07:25 do-coreos01-master kernel: device veth0eb461d left promiscuous mode
Mar 08 16:07:25 do-coreos01-master kernel: docker0: port 1(veth0eb461d) entered disabled state
Mar 08 16:07:25 do-coreos01-master systemd-networkd[603]: veth0eb461d     : lost carrier
Mar 08 16:07:25 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:25Z" level="info" msg="+job log(die, 9eade23528a8b23a10a3154e538ba49aa7db25d73b8cdd2127de7d0e328e2978, imjMar 08 16:07:25 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:25Z" level="info" msg="-job log(die, 9eade23528a8b23a10a3154e538ba49aa7db25d73b8cdd2127de7d0e328e2978, imjMar 08 16:07:25 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:25Z" level="info" msg="+job release_interface(9eade23528a8b23a10a3154e538ba49aa7db25d73b8cdd2127de7d0e328eMar 08 16:07:25 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:25Z" level="info" msg="-job attach(9eade23528a8b23a10a3154e538ba49aa7db25d73b8cdd2127de7d0e328e2978) = OK Mar 08 16:07:25 do-coreos01-master systemd-networkd[603]: veth0eb461d     : could not find udev device: No such device
Mar 08 16:07:25 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:25Z" level="info" msg="POST /v1.16/containers/9eade23528a8b23a10a3154e538ba49aa7db25d73b8cdd2127de7d0e328eMar 08 16:07:25 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:25Z" level="info" msg="+job wait(9eade23528a8b23a10a3154e538ba49aa7db25d73b8cdd2127de7d0e328e2978)"
Mar 08 16:07:25 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:25Z" level="info" msg="-job release_interface(9eade23528a8b23a10a3154e538ba49aa7db25d73b8cdd2127de7d0e328eMar 08 16:07:25 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:25Z" level="info" msg="+job log(stop, 9eade23528a8b23a10a3154e538ba49aa7db25d73b8cdd2127de7d0e328e2978, imMar 08 16:07:25 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:25Z" level="info" msg="-job log(stop, 9eade23528a8b23a10a3154e538ba49aa7db25d73b8cdd2127de7d0e328e2978, imMar 08 16:07:25 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:25Z" level="info" msg="-job stop(nginx) = OK (0)"
Mar 08 16:07:25 do-coreos01-master dockerd[631]: time="2015-03-08T16:07:25Z" level="info" msg="-job wait(9eade23528a8b23a10a3154e538ba49aa7db25d73b8cdd2127de7d0e328e2978) = OK (0Mar 08 16:07:25 do-coreos01-master systemd[1]: nginx.service: main process exited, code=exited, status=255/n/a
Mar 08 16:07:25 do-coreos01-master docker[26489]: nginx
Mar 08 16:07:25 do-coreos01-master systemd[1]: Stopped nginx.service.
Mar 08 16:07:25 do-coreos01-master systemd[1]: Unit nginx.service entered failed state.
Mar 08 16:07:25 do-coreos01-master systemd[1]: nginx.service failed.
Mar 08 16:07:25 do-coreos01-master systemd-networkd[603]: docker0         : lost carrier
Mar 08 16:07:27 do-coreos01-master ntpd[472]: Deleting interface #14 veth7c483f1, fe80::e893:58ff:fe61:1a5%10#123, interface stats: received=0, sent=0, dropped=0, active_time=225Mar 08 16:07:27 do-coreos01-master ntpd[472]: Deleting interface #17 veth0eb461d, fe80::18eb:3bff:fed4:661f%16#123, interface stats: received=0, sent=0, dropped=0, active_time=20Mar 08 16:07:27 do-coreos01-master ntpd[472]: 8 Mar 16:07:27 ntpd[472]: Deleting interface #14 veth7c483f1, fe80::e893:58ff:fe61:1a5%10#123, interface stats: received=0, sent=0, Mar 08 16:07:27 do-coreos01-master ntpd[472]: 8 Mar 16:07:27 ntpd[472]: Deleting interface #17 veth0eb461d, fe80::18eb:3bff:fed4:661f%16#123, interface stats: received=0, sent=0,Mar 08 16:07:30 do-coreos01-master systemd[1]: Starting Generate /run/coreos/motd...
Mar 08 16:07:30 do-coreos01-master systemd[1]: Failed to set memory.limit_in_bytes on : Invalid argument
Mar 08 16:07:30 do-coreos01-master systemd[1]: Failed to reset devices.list on /system.slice: Invalid argument
Mar 08 16:07:30 do-coreos01-master systemd[1]: Started Generate /run/coreos/motd.
Mar 08 16:07:34 do-coreos01-master systemd[1]: Starting OpenSSH per-connection server daemon (115.231.218.130:50731)...
Mar 08 16:07:34 do-coreos01-master systemd[1]: Started OpenSSH per-connection server daemon (115.231.218.130:50731).
Mar 08 16:07:39 do-coreos01-master sshd[26604]: Received disconnect from 115.231.218.130: 11:  [preauth]
Mar 08 16:07:56 do-coreos01-master systemd[1]: Starting OpenSSH per-connection server daemon (109.153.87.231:64260)...
Mar 08 16:07:56 do-coreos01-master systemd[1]: Started OpenSSH per-connection server daemon (109.153.87.231:64260).
Mar 08 16:07:57 do-coreos01-master sshd[26608]: Accepted publickey for core from 109.153.87.231 port 64260 ssh2: RSA d6:cc:49:3b:7a:76:17:e1:42:97:43:92:fe:cd:84:e6
Mar 08 16:08:30 do-coreos01-master systemd[1]: Starting Generate /run/coreos/motd...
Mar 08 16:08:30 do-coreos01-master systemd[1]: Started Generate /run/coreos/motd.
```

```shell
core@do-coreos01-master ~ $ systemctl status fleet -l
● fleet.service - fleet daemon
   Loaded: loaded (/usr/lib64/systemd/system/fleet.service; static; vendor preset: disabled)
  Drop-In: /run/systemd/system/fleet.service.d
           └─20-cloudinit.conf
   Active: active (running) since Sun 2015-03-08 09:51:37 UTC; 6h ago
 Main PID: 608 (fleetd)
   CGroup: /system.slice/fleet.service
           └─608 /usr/bin/fleetd

Mar 08 16:07:19 do-coreos01-master fleetd[608]: ERROR manager.go:136: Failed to trigger systemd unit devnews-core@82.service start: Unit devnews-core-discovery@82.service failed to load: No such file or directory.
Mar 08 16:07:19 do-coreos01-master fleetd[608]: INFO reconcile.go:321: AgentReconciler completed task: type=StartUnit job=devnews-core@82.service reason="unit currently loaded but desired state is launched"
Mar 08 16:07:19 do-coreos01-master fleetd[608]: ERROR manager.go:136: Failed to trigger systemd unit nginx.service start: Unit nginx.service failed to load: No such file or directory.
Mar 08 16:07:19 do-coreos01-master fleetd[608]: INFO reconcile.go:321: AgentReconciler completed task: type=StartUnit job=nginx.service reason="unit currently loaded but desired state is launched"
Mar 08 16:07:19 do-coreos01-master fleetd[608]: ERROR manager.go:136: Failed to trigger systemd unit blog-jacob-uk-com-discovery@90.service start: Unit blog-jacob-uk-com@90.service failed to load: No such file or directory.
Mar 08 16:07:19 do-coreos01-master fleetd[608]: INFO reconcile.go:321: AgentReconciler completed task: type=StartUnit job=blog-jacob-uk-com-discovery@90.service reason="unit currently loaded but desired state is launched"
Mar 08 16:07:19 do-coreos01-master fleetd[608]: ERROR manager.go:136: Failed to trigger systemd unit blog-jacob-uk-com@90.service start: Unit blog-jacob-uk-com@90.service failed to load: No such file or directory.
Mar 08 16:07:19 do-coreos01-master fleetd[608]: INFO reconcile.go:321: AgentReconciler completed task: type=StartUnit job=blog-jacob-uk-com@90.service reason="unit currently loaded but desired state is launched"
Mar 08 16:07:19 do-coreos01-master fleetd[608]: ERROR manager.go:136: Failed to trigger systemd unit devnews-core-discovery@82.service start: Unit devnews-core-discovery@82.service failed to load: No such file or directory.
Mar 08 16:07:19 do-coreos01-master fleetd[608]: INFO reconcile.go:321: AgentReconciler completed task: type=StartUnit job=devnews-core-discovery@82.service reason="unit currently loaded but desired state is launched"
```

**Comment by patrickbcullen** [comment] 2015-03-11 02:37
Similar issue for me as well. I am seeing the No such file or directory error on every other deployment when using templates. For service files that don't use templates, I don't have this problem. By templates I mean the service files with the @ sign in it.

**Comment by patrickbcullen** [comment] 2015-03-11 03:19
I just did a quick test of fleet 0.8.3 vs 0.9.0 and the problem does not happen on 0.8.3. Looks like a bug with 0.9.0.

**Comment by tleyden** [comment] 2015-03-12 15:16
> For service files that don't use templates, I don't have this problem. By templates I mean the service files with the @ sign in it.

I tried switching to non-templates, and it didn't fix the issue for me.

**Comment by patrickbcullen** [comment] 2015-03-13 01:03
The only solution I could find was rolling back to 522.6.0 for CoreOS. If you are running on EC2 you can find the AMI that supports this version. Then you need to disable the update-service or it will automatically upgrade you to the broken CoreOS version. To disable the update server add this stanze to your EC2 user-data string.

#cloud-config
coreos:
  units:
  - name: update-engine.service
    command: stop
    mask: true

**Comment by tleyden** [comment] 2015-03-13 01:26
Good to know, but in my case I need the fix for https://github.com/coreos/bugs/issues/186#issuecomment-74964152, which is in a later version of CoreOS (584.0.0). 

Also, after buying into the *raison d'etre* of the existence of CoreOS (Brandon Phillips did a great podcast on [cloudcast](http://www.thecloudcast.net/2013/09/the-cloudcast-107-coreos-and-linux.html) which explains this), I've decided that if I'm disabling auto-updating / auto-rebooting (aka "the chaos monkey") then I'm not using CoreOS as it was intended to be used.

**Comment by bcwaldon** [comment] 2015-03-20 03:43
@imjacobclark Can you share the contents of your unit files that display this behavior?

**Comment by bcwaldon** [comment] 2015-03-20 03:49
Likely #1158

**Comment by bcwaldon** [comment] 2015-03-31 00:45
Closing as fixed by https://github.com/coreos/fleet/pull/1168. Please reopen once you've had a chance to try that fix out.

**Closed by bcwaldon** 2015-03-31 00:45 UTC
Labels: needs-more
