### ISSUE TITLE
intermittent failures of TestWrongHostKeyFile in github.com/coreos/fleet/ssh under docker

### ISSUE THREAD

**Issue by mischief** [coreos/fleet#1279] opened 2015-06-29 22:12 UTC
```
$ ./test-docker 
Building fleetd...
Building fleetctl...
Running tests...
ok      github.com/coreos/fleet/agent   0.009s  coverage: 70.6% of statements
ok      github.com/coreos/fleet/api     0.024s  coverage: 80.4% of statements
ok      github.com/coreos/fleet/config  0.005s  coverage: 100.0% of statements
ok      github.com/coreos/fleet/engine  0.010s  coverage: 54.5% of statements
ok      github.com/coreos/fleet/fleetctl        0.099s  coverage: 23.2% of statements
ok      github.com/coreos/fleet/job     0.018s  coverage: 89.2% of statements
ok      github.com/coreos/fleet/machine 0.035s  coverage: 35.1% of statements
ok      github.com/coreos/fleet/pkg     0.023s  coverage: 81.9% of statements
ok      github.com/coreos/fleet/pkg/lease       0.003s  coverage: 14.3% of statements
ok      github.com/coreos/fleet/registry        0.009s  coverage: 26.7% of statements
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the RSA key sent by the remote host is
93:d8:4c:0d:b2:c3:2e:da:b9:c0:67:db:e4:8f:95:04.
Please contact your system administrator.
Add correct host key in ../fixtures/known_hosts to get rid of this message.
Host key verification failed.
Host key verification failed.
Warning: Permanently added '[192.0.2.10]:2222' (RSA) to the list of known hosts.
--- FAIL: TestWrongHostKeyFile (0.00 seconds)
        known_hosts_test.go:156: should fail to read wrong host file
WARN known_hosts.go:240: ../fixtures/bad_known_hosts:1 - bad format (insufficient fields)
WARN known_hosts.go:240: ../fixtures/bad_known_hosts:2 - error parsing key: ssh: no key found
FAIL
coverage: 42.1% of statements
FAIL    github.com/coreos/fleet/ssh     0.006s
ok      github.com/coreos/fleet/systemd 0.003s  coverage: 15.5% of statements
ok      github.com/coreos/fleet/unit    0.004s  coverage: 88.4% of statements
```

**Comment by dongsupark** [comment] 2016-12-15 15:42
I cannot reproduce, at least with docker 1.8.2. `test-docker` works fine.
I'd assume that this old bug has been fixed by upstream docker.

**Closed by dongsupark** 2016-12-15 15:42 UTC
Labels: kind/bug
