### ISSUE TITLE
[Feature request] Allow MachineOf to support wildcards

### ISSUE THREAD

**Issue by Dynom** [coreos/fleet#1298] opened 2015-07-07 07:45 UTC
Hi,

In #1297 I describe a problem I had with a presumption and an ochestration problem because the `MachineOf` directive doesn't support the syntax that `Conflicts` does, as documented here: https://coreos.com/docs/launching-containers/launching/fleet-unit-files/

I would like to see the following syntax supported:

`MachineOf=leading@*.service`

The semantics are that I do not necessarily care about the specific unit instance, only the unit. And I want to schedule several, of the same, unit with that `leading` unit.

**Comment by bcwaldon** [comment] 2015-07-09 20:38
duplicate of https://github.com/coreos/fleet/issues/494

**Closed by bcwaldon** 2015-07-09 20:38 UTC
