### ISSUE TITLE
handshake failed: ssh: unexpected message type 1 (expected 52)

### ISSUE THREAD

**Issue by jfromaniello** [coreos/fleet#565] opened 2014-06-23 23:09 UTC
I reported this on coreos/coreos-vagrant#106 but it also happens when trying to manage a cluster on EC2.

It happens when you have more than 7 keys in the ssh-agent. 

My ~/.ssh/config says what key should be used for that host but the ssh tunneling feature seems to ignore that.

**Comment by jonboulle** [comment] 2016-01-26 14:02
Let's figure something out for this one before 1.0

**Comment by antrik** [comment] 2016-03-03 16:49
@jonboulle you wrote "let's figure something out before 1.0", but set the milestone to 0.13 -- is this intentional?...

**Comment by kevin-brown** [comment] 2016-03-08 20:39
I was able to reproduce this issue pretty consistently on Ubuntu once my SSH agent had more than 5 keys added to it. Removing keys fixed the issue, though it'd be nice to not have to work around this.

Note that Ubuntu also has a keychain, and you can't remove keys added using it from the agent with `ssh-add -d`, they will be automatically added back in.

**Comment by kayrus** [comment] 2016-03-08 20:48
We have to add tests first.

**Comment by kayrus** [comment] 2016-03-15 16:37
If we modify upstream `Godeps/_workspace/src/golang.org/x/crypto/ssh/client_auth.go` and add `SSH2_MSG_DISCONNECT` support we can handle this "unexpected" message correctly. Because it actually means `2016/03/15 16:35:00 Received *ssh.disconnectMsg ssh: disconnect reason 2: Too many authentication failures (<nil>)`. There is nothing to do in fleet code, only proper error handling. The error relates to SSH daemon configuration.

```diff
diff --git a/Godeps/_workspace/src/golang.org/x/crypto/ssh/client_auth.go b/Godeps/_workspace/src/golang.org/x/crypto/ssh/client_auth.go
index e15be3e..fbb6806 100644
--- a/Godeps/_workspace/src/golang.org/x/crypto/ssh/client_auth.go
+++ b/Godeps/_workspace/src/golang.org/x/crypto/ssh/client_auth.go
@@ -8,6 +8,7 @@ import (
        "bytes"
        "errors"
        "fmt"
+       "log"
        "io"
 )
 
@@ -283,6 +284,8 @@ func confirmKeyAck(key PublicKey, c packetConn) (bool, error) {
                case msgUserAuthFailure:
                        return false, nil
                default:
+                       msg, err := decode(packet)
+                       log.Printf("Received %T %v (%v)", msg, msg, err)
                        return false, unexpectedMessageError(msgUserAuthSuccess, packet[0])
                }
        }
@@ -324,6 +327,8 @@ func handleAuthResponse(c packetConn) (bool, []string, error) {
                case msgDisconnect:
                        return false, nil, io.EOF
                default:
+                       msg, err := decode(packet)
+                       log.Printf("Received %T %v (%v)", msg, msg, err)
                        return false, nil, unexpectedMessageError(msgUserAuthSuccess, packet[0])
                }
        }
@@ -387,6 +392,8 @@ func (cb KeyboardInteractiveChallenge) auth(session []byte, user string, c packe
                case msgUserAuthSuccess:
                        return true, nil, nil
                default:
+                       msg, err := decode(packet)
+                       log.Printf("Received %T %v (%v)", msg, msg, err)
                        return false, nil, unexpectedMessageError(msgUserAuthInfoRequest, packet[0])
                }
 

```

**Comment by brianredbeard** [comment] 2016-03-15 16:41
@kayrus makes sense (especially after reading the [IANA defined parameters](http://www.iana.org/assignments/ssh-parameters/ssh-parameters.xml#ssh-parameters-1)).  What's the plan of attack for taking this upstream?

**Comment by kayrus** [comment] 2016-03-16 13:58
@brianredbeard PR is here: https://go-review.googlesource.com/#/c/20687/

**Comment by kayrus** [comment] 2016-03-17 14:01
[this](https://go-review.googlesource.com/#/c/20687/) fix is closed in favor of https://go-review.googlesource.com/#/c/20801/

**Comment by kayrus** [comment] 2016-03-29 15:57
Fixed: https://github.com/golang/crypto/commit/9e7f5dc375abeb9619ea3c5c58502c428f457aa2, we have to update godeps.

**Closed** 2016-03-31 12:56 UTC
Labels: dependency/external, help wanted, kind/bug
