### ISSUE TITLE
Fleet API and new lines

### ISSUE THREAD

**Issue by tj-corrigan** [coreos/fleet#1538] opened 2016-04-07 22:36 UTC
We have recently run into a problem when using the fleet API to create large units. Due to a limitation in systemd (see https://github.com/coreos/fleet/issues/992) we can't have a single line over 2048 characters. Unfortunately our `ExectStart` commands occasionally get longer than this limit. I was hoping that I could instead break up the line to produce something that looks like:

```
[Service]
ExecStart=/usr/bin/docker run --name failing \
  -e longstring \
  -e longstring \
  container:tag
```

I can't seem to find a way to make this work via the API though. I was thinking something like

`curl -X PUT localhost:41337/fleet/v1/units/failing.service -H "Content-Type: application/json" -d '{"name":"failing.service","options":[{"section":"Service","name":"ExecStart","value":"/usr/bin/docker run --name=failing \\ \n -e longstring \\ \n -e longstring container:tag"}],"desiredState":"launched"}'`

This command will go through successfully but the unit never gets created (and I can no longer submit things to that name). Looking at the logs I see:

`Apr 07 22:34:07 core-1 fleetd[1033]: ERROR unit.go:72: error parsing Unit(635c78f9bc0771908607a36102f98d2afbd52bff): unexpected newline encountered while parsing option name`

Any thoughts?

**Comment by kayrus** [comment] 2016-04-08 14:08
@tj-corrigan confirmed. when you put unit file manually into the systemd directory with the contents below:

```ini
systemctl cat hello
# /etc/systemd/system/hello.service
[Unit]

[Service]
ExecStart=/bin/bash -c "\
while true;\
 do echo Hello, World!; sleep 1;\
done\
"
```

It works.

When you submit same unit file withing fleetctl, it skips newlines:

```ini
[Service]
ExecStart=/bin/bash -c " while true;  do echo Hello, World!; sleep 1; done "
```

But it works too. The only unexpected behavior, that local file's sha1sum and registry sha1sum differ:

```sh
$ sha1sum hello.service 
a8ffdf96a1f50b372fb6cbe5d2971463bc120e9c  hello.service
$ etcdctl get /_coreos.com/fleet/job/hello.service/object | sed -r 's#.*UnitHash":\[([0-9,]+)\].*#\1#g' | tr -d '\n' | xargs -d ',' printf "%02x" ; echo
15ea242bf6eae53bf1d88d14d9aeef595c30ae94
```

Relates to #1539

**Comment by kayrus** [comment] 2016-04-08 14:20
`fleetctl --experimental-api=false start hello.service` works as expected.

**Comment by kayrus** [comment] 2016-04-08 15:01
@tj-corrigan btw, in your case proper json code should be (just remove whitespace between `\\` and `\n`):

```sh
curl -X PUT localhost:41337/fleet/v1/units/failing.service -H "Content-Type: application/json" -d '{"name":"failing.service","options":[{"section":"Service","name":"ExecStart","value":"/usr/bin/docker run --name=failing \\\n -e longstring \\\n -e longstring container:tag"}],"desiredState":"launched"}'
```

**Comment by tj-corrigan** [comment] 2016-04-08 15:09
Thanks, I tried a bunch of different permutations trying to get it to work but hadn't thought of that one.  Your snippet above results in the following file on the executing host:

```
[Service]
ExecStart=/usr/bin/docker run --name=failing   -e longstring   -e longstring container:tag
```

Looks like now we just need to work through why fleet isn't passing along the new lines.

**Comment by kayrus** [comment] 2016-04-08 15:09
@tj-corrigan issue with the skipped newlines was fixed in master branch.

**Comment by kayrus** [comment] 2016-04-08 15:21
@tj-corrigan here is the patch which fixes the problem https://github.com/jonboulle/go-systemd/commit/fe849504bbc46e617f21ec9a66357a5a6cfd9104

**Closed by kayrus** 2016-04-08 15:21 UTC

**Comment by tj-corrigan** [comment] 2016-04-08 15:42
@kayrus I'm still running into problems running the current version of CoreOS stable (899.15.0). 

Here is an example that shows the problem (sorry it has to be long):

```
curl -X PUT localhost:41337/fleet/v1/units/long.service -H "Content-Type: application/json" -d  '{"name":"long.service","options":[{"section":"Service","name":"ExecStart","value":"/usr/bin/docker run --name=long -e ENV_VAR1=abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz \\\n -e ENV_VAR2=abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz alpine:latest env"}],"desiredState":"launched"}'
```

If the two environmental variables were on separate lines it should go through without running into the 2048 character limit. However that new line never makes it through and it causes the unit to fail to start.

**Comment by kayrus** [comment] 2016-04-08 18:18
@tj-corrigan did you try to compile latest master branch? CoreOS 899.15.0 still uses fleet 0.11.x. Current master branch will be tagged as 0.12.0

**Comment by tj-corrigan** [comment] 2016-04-08 18:38
@kayrus Good to hear. I'll wait for fleet 0.12.0 to make it into the CoreOS releases. Thanks for your help!

**Comment by fxfitz** [comment] 2017-01-11 14:56
We're running into this problem in our production environment as well, and it looks like CoreOS stable (and beta and alpha) are still using fleet 0.11.x.

@tj-corrigan Did you find a good work around? We're not sure what to do at this point. :-/

**Comment by tj-corrigan** [comment] 2017-01-11 15:13
We switched things up a bit so this no longer affects us. One possible workaround would just have your ExecStart command point to some shell script where you store the longer command.

**Comment by fxfitz** [comment] 2017-01-11 15:17
Okay, thanks.

@kayrus Any ideas for a valid work around?
